# Generated by Django 5.0.3 on 2024-03-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
