# Generated by Django 5.0.3 on 2024-05-16 14:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_service_contact_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='apsolife_images/'),
            preserve_default=False,
        ),
    ]
