# Generated by Django 5.0.3 on 2024-03-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
