# Generated by Django 5.0.3 on 2024-03-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_method',
            field=models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], default='call', max_length=50),
            preserve_default=False,
        ),
    ]
