# Generated by Django 5.0.3 on 2024-03-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
